image:
  repository: ghcr.io/refinedstone/newsbot
  tag: "0.0.1"
  pullPolicy: IfNotPresent

#service:
#  type: ClusterIP
#  port: 21000        # 클러스터 내부 접근 포트
#  targetPort: 21000  # 실제 컨테이너 내부 애플리케이션 포트
service:
  type: NodePort
  port: 21000
  targetPort: 21000
  nodePort: 32100 # 테스트용으로 포트포워딩

env:
  - name: JAVA_TOOL_OPTIONS
    value: "-Dotel.exporter=logging" # Tempo 없을 때 임시 적용

replicaCount: 1
resources: {}

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80